// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.7
// 	protoc        v6.31.1
// source: pkg/infrastructure/pb/auth_server.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RequestUserLogin struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         string                 `protobuf:"bytes,1,opt,name=Email,proto3" json:"Email,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=Password,proto3" json:"Password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RequestUserLogin) Reset() {
	*x = RequestUserLogin{}
	mi := &file_pkg_infrastructure_pb_auth_server_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestUserLogin) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestUserLogin) ProtoMessage() {}

func (x *RequestUserLogin) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_infrastructure_pb_auth_server_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestUserLogin.ProtoReflect.Descriptor instead.
func (*RequestUserLogin) Descriptor() ([]byte, []int) {
	return file_pkg_infrastructure_pb_auth_server_proto_rawDescGZIP(), []int{0}
}

func (x *RequestUserLogin) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *RequestUserLogin) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type ResponseUserLogin struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccessToken   string                 `protobuf:"bytes,1,opt,name=AccessToken,proto3" json:"AccessToken,omitempty"`
	RefreshToken  string                 `protobuf:"bytes,2,opt,name=RefreshToken,proto3" json:"RefreshToken,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,3,opt,name=ErrorMessage,proto3" json:"ErrorMessage,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResponseUserLogin) Reset() {
	*x = ResponseUserLogin{}
	mi := &file_pkg_infrastructure_pb_auth_server_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResponseUserLogin) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResponseUserLogin) ProtoMessage() {}

func (x *ResponseUserLogin) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_infrastructure_pb_auth_server_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResponseUserLogin.ProtoReflect.Descriptor instead.
func (*ResponseUserLogin) Descriptor() ([]byte, []int) {
	return file_pkg_infrastructure_pb_auth_server_proto_rawDescGZIP(), []int{1}
}

func (x *ResponseUserLogin) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

func (x *ResponseUserLogin) GetRefreshToken() string {
	if x != nil {
		return x.RefreshToken
	}
	return ""
}

func (x *ResponseUserLogin) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

type RequestOtpVefification struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TempToken     string                 `protobuf:"bytes,1,opt,name=TempToken,proto3" json:"TempToken,omitempty"`
	Otp           string                 `protobuf:"bytes,2,opt,name=Otp,proto3" json:"Otp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RequestOtpVefification) Reset() {
	*x = RequestOtpVefification{}
	mi := &file_pkg_infrastructure_pb_auth_server_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestOtpVefification) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestOtpVefification) ProtoMessage() {}

func (x *RequestOtpVefification) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_infrastructure_pb_auth_server_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestOtpVefification.ProtoReflect.Descriptor instead.
func (*RequestOtpVefification) Descriptor() ([]byte, []int) {
	return file_pkg_infrastructure_pb_auth_server_proto_rawDescGZIP(), []int{2}
}

func (x *RequestOtpVefification) GetTempToken() string {
	if x != nil {
		return x.TempToken
	}
	return ""
}

func (x *RequestOtpVefification) GetOtp() string {
	if x != nil {
		return x.Otp
	}
	return ""
}

type ResponseOtpVerification struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccessToken   string                 `protobuf:"bytes,1,opt,name=AccessToken,proto3" json:"AccessToken,omitempty"`
	RefreshToken  string                 `protobuf:"bytes,2,opt,name=RefreshToken,proto3" json:"RefreshToken,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,3,opt,name=ErrorMessage,proto3" json:"ErrorMessage,omitempty"`
	Otp           string                 `protobuf:"bytes,4,opt,name=Otp,proto3" json:"Otp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResponseOtpVerification) Reset() {
	*x = ResponseOtpVerification{}
	mi := &file_pkg_infrastructure_pb_auth_server_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResponseOtpVerification) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResponseOtpVerification) ProtoMessage() {}

func (x *ResponseOtpVerification) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_infrastructure_pb_auth_server_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResponseOtpVerification.ProtoReflect.Descriptor instead.
func (*ResponseOtpVerification) Descriptor() ([]byte, []int) {
	return file_pkg_infrastructure_pb_auth_server_proto_rawDescGZIP(), []int{3}
}

func (x *ResponseOtpVerification) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

func (x *ResponseOtpVerification) GetRefreshToken() string {
	if x != nil {
		return x.RefreshToken
	}
	return ""
}

func (x *ResponseOtpVerification) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *ResponseOtpVerification) GetOtp() string {
	if x != nil {
		return x.Otp
	}
	return ""
}

type SignUpRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	UserName        string                 `protobuf:"bytes,1,opt,name=UserName,proto3" json:"UserName,omitempty"`
	Name            string                 `protobuf:"bytes,2,opt,name=Name,proto3" json:"Name,omitempty"`
	Email           string                 `protobuf:"bytes,4,opt,name=Email,proto3" json:"Email,omitempty"`
	Password        string                 `protobuf:"bytes,5,opt,name=Password,proto3" json:"Password,omitempty"`
	ConfirmPassword string                 `protobuf:"bytes,6,opt,name=ConfirmPassword,proto3" json:"ConfirmPassword,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *SignUpRequest) Reset() {
	*x = SignUpRequest{}
	mi := &file_pkg_infrastructure_pb_auth_server_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignUpRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignUpRequest) ProtoMessage() {}

func (x *SignUpRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_infrastructure_pb_auth_server_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignUpRequest.ProtoReflect.Descriptor instead.
func (*SignUpRequest) Descriptor() ([]byte, []int) {
	return file_pkg_infrastructure_pb_auth_server_proto_rawDescGZIP(), []int{4}
}

func (x *SignUpRequest) GetUserName() string {
	if x != nil {
		return x.UserName
	}
	return ""
}

func (x *SignUpRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *SignUpRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *SignUpRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *SignUpRequest) GetConfirmPassword() string {
	if x != nil {
		return x.ConfirmPassword
	}
	return ""
}

type SignUpResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=Token,proto3" json:"Token,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,2,opt,name=ErrorMessage,proto3" json:"ErrorMessage,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SignUpResponse) Reset() {
	*x = SignUpResponse{}
	mi := &file_pkg_infrastructure_pb_auth_server_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignUpResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignUpResponse) ProtoMessage() {}

func (x *SignUpResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_infrastructure_pb_auth_server_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignUpResponse.ProtoReflect.Descriptor instead.
func (*SignUpResponse) Descriptor() ([]byte, []int) {
	return file_pkg_infrastructure_pb_auth_server_proto_rawDescGZIP(), []int{5}
}

func (x *SignUpResponse) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *SignUpResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

type RequestForgotPass struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         string                 `protobuf:"bytes,1,opt,name=Email,proto3" json:"Email,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RequestForgotPass) Reset() {
	*x = RequestForgotPass{}
	mi := &file_pkg_infrastructure_pb_auth_server_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestForgotPass) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestForgotPass) ProtoMessage() {}

func (x *RequestForgotPass) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_infrastructure_pb_auth_server_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestForgotPass.ProtoReflect.Descriptor instead.
func (*RequestForgotPass) Descriptor() ([]byte, []int) {
	return file_pkg_infrastructure_pb_auth_server_proto_rawDescGZIP(), []int{6}
}

func (x *RequestForgotPass) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

type ResponseForgotPass struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=Token,proto3" json:"Token,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,2,opt,name=ErrorMessage,proto3" json:"ErrorMessage,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResponseForgotPass) Reset() {
	*x = ResponseForgotPass{}
	mi := &file_pkg_infrastructure_pb_auth_server_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResponseForgotPass) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResponseForgotPass) ProtoMessage() {}

func (x *ResponseForgotPass) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_infrastructure_pb_auth_server_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResponseForgotPass.ProtoReflect.Descriptor instead.
func (*ResponseForgotPass) Descriptor() ([]byte, []int) {
	return file_pkg_infrastructure_pb_auth_server_proto_rawDescGZIP(), []int{7}
}

func (x *ResponseForgotPass) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *ResponseForgotPass) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

type RequestResetPass struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Otp             string                 `protobuf:"bytes,1,opt,name=Otp,proto3" json:"Otp,omitempty"`
	Password        string                 `protobuf:"bytes,2,opt,name=Password,proto3" json:"Password,omitempty"`
	ConfirmPassword string                 `protobuf:"bytes,3,opt,name=ConfirmPassword,proto3" json:"ConfirmPassword,omitempty"`
	TempToken       string                 `protobuf:"bytes,4,opt,name=TempToken,proto3" json:"TempToken,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *RequestResetPass) Reset() {
	*x = RequestResetPass{}
	mi := &file_pkg_infrastructure_pb_auth_server_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestResetPass) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestResetPass) ProtoMessage() {}

func (x *RequestResetPass) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_infrastructure_pb_auth_server_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestResetPass.ProtoReflect.Descriptor instead.
func (*RequestResetPass) Descriptor() ([]byte, []int) {
	return file_pkg_infrastructure_pb_auth_server_proto_rawDescGZIP(), []int{8}
}

func (x *RequestResetPass) GetOtp() string {
	if x != nil {
		return x.Otp
	}
	return ""
}

func (x *RequestResetPass) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *RequestResetPass) GetConfirmPassword() string {
	if x != nil {
		return x.ConfirmPassword
	}
	return ""
}

func (x *RequestResetPass) GetTempToken() string {
	if x != nil {
		return x.TempToken
	}
	return ""
}

type ResponseResetPass struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=Token,proto3" json:"Token,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,2,opt,name=ErrorMessage,proto3" json:"ErrorMessage,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResponseResetPass) Reset() {
	*x = ResponseResetPass{}
	mi := &file_pkg_infrastructure_pb_auth_server_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResponseResetPass) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResponseResetPass) ProtoMessage() {}

func (x *ResponseResetPass) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_infrastructure_pb_auth_server_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResponseResetPass.ProtoReflect.Descriptor instead.
func (*ResponseResetPass) Descriptor() ([]byte, []int) {
	return file_pkg_infrastructure_pb_auth_server_proto_rawDescGZIP(), []int{9}
}

func (x *ResponseResetPass) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *ResponseResetPass) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

var File_pkg_infrastructure_pb_auth_server_proto protoreflect.FileDescriptor

const file_pkg_infrastructure_pb_auth_server_proto_rawDesc = "" +
	"\n" +
	"'pkg/infrastructure/pb/auth_server.proto\x12\x04auth\"D\n" +
	"\x10RequestUserLogin\x12\x14\n" +
	"\x05Email\x18\x01 \x01(\tR\x05Email\x12\x1a\n" +
	"\bPassword\x18\x02 \x01(\tR\bPassword\"}\n" +
	"\x11ResponseUserLogin\x12 \n" +
	"\vAccessToken\x18\x01 \x01(\tR\vAccessToken\x12\"\n" +
	"\fRefreshToken\x18\x02 \x01(\tR\fRefreshToken\x12\"\n" +
	"\fErrorMessage\x18\x03 \x01(\tR\fErrorMessage\"H\n" +
	"\x16RequestOtpVefification\x12\x1c\n" +
	"\tTempToken\x18\x01 \x01(\tR\tTempToken\x12\x10\n" +
	"\x03Otp\x18\x02 \x01(\tR\x03Otp\"\x95\x01\n" +
	"\x17ResponseOtpVerification\x12 \n" +
	"\vAccessToken\x18\x01 \x01(\tR\vAccessToken\x12\"\n" +
	"\fRefreshToken\x18\x02 \x01(\tR\fRefreshToken\x12\"\n" +
	"\fErrorMessage\x18\x03 \x01(\tR\fErrorMessage\x12\x10\n" +
	"\x03Otp\x18\x04 \x01(\tR\x03Otp\"\x9b\x01\n" +
	"\rSignUpRequest\x12\x1a\n" +
	"\bUserName\x18\x01 \x01(\tR\bUserName\x12\x12\n" +
	"\x04Name\x18\x02 \x01(\tR\x04Name\x12\x14\n" +
	"\x05Email\x18\x04 \x01(\tR\x05Email\x12\x1a\n" +
	"\bPassword\x18\x05 \x01(\tR\bPassword\x12(\n" +
	"\x0fConfirmPassword\x18\x06 \x01(\tR\x0fConfirmPassword\"J\n" +
	"\x0eSignUpResponse\x12\x14\n" +
	"\x05Token\x18\x01 \x01(\tR\x05Token\x12\"\n" +
	"\fErrorMessage\x18\x02 \x01(\tR\fErrorMessage\")\n" +
	"\x11RequestForgotPass\x12\x14\n" +
	"\x05Email\x18\x01 \x01(\tR\x05Email\"N\n" +
	"\x12ResponseForgotPass\x12\x14\n" +
	"\x05Token\x18\x01 \x01(\tR\x05Token\x12\"\n" +
	"\fErrorMessage\x18\x02 \x01(\tR\fErrorMessage\"\x88\x01\n" +
	"\x10RequestResetPass\x12\x10\n" +
	"\x03Otp\x18\x01 \x01(\tR\x03Otp\x12\x1a\n" +
	"\bPassword\x18\x02 \x01(\tR\bPassword\x12(\n" +
	"\x0fConfirmPassword\x18\x03 \x01(\tR\x0fConfirmPassword\x12\x1c\n" +
	"\tTempToken\x18\x04 \x01(\tR\tTempToken\"M\n" +
	"\x11ResponseResetPass\x12\x14\n" +
	"\x05Token\x18\x01 \x01(\tR\x05Token\x12\"\n" +
	"\fErrorMessage\x18\x02 \x01(\tR\fErrorMessage2\xe4\x02\n" +
	"\vAuthService\x127\n" +
	"\n" +
	"UserSignUp\x12\x13.auth.SignUpRequest\x1a\x14.auth.SignUpResponse\x12P\n" +
	"\x11UserOTPVerication\x12\x1c.auth.RequestOtpVefification\x1a\x1d.auth.ResponseOtpVerification\x12<\n" +
	"\tUserLogin\x12\x16.auth.RequestUserLogin\x1a\x17.auth.ResponseUserLogin\x12J\n" +
	"\x15ForgotPasswordRequest\x12\x17.auth.RequestForgotPass\x1a\x18.auth.ResponseForgotPass\x12@\n" +
	"\rResetPassword\x12\x16.auth.RequestResetPass\x1a\x17.auth.ResponseResetPassB\x19Z\x17./pkg/infrastructure/pbb\x06proto3"

var (
	file_pkg_infrastructure_pb_auth_server_proto_rawDescOnce sync.Once
	file_pkg_infrastructure_pb_auth_server_proto_rawDescData []byte
)

func file_pkg_infrastructure_pb_auth_server_proto_rawDescGZIP() []byte {
	file_pkg_infrastructure_pb_auth_server_proto_rawDescOnce.Do(func() {
		file_pkg_infrastructure_pb_auth_server_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_infrastructure_pb_auth_server_proto_rawDesc), len(file_pkg_infrastructure_pb_auth_server_proto_rawDesc)))
	})
	return file_pkg_infrastructure_pb_auth_server_proto_rawDescData
}

var file_pkg_infrastructure_pb_auth_server_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_pkg_infrastructure_pb_auth_server_proto_goTypes = []any{
	(*RequestUserLogin)(nil),        // 0: auth.RequestUserLogin
	(*ResponseUserLogin)(nil),       // 1: auth.ResponseUserLogin
	(*RequestOtpVefification)(nil),  // 2: auth.RequestOtpVefification
	(*ResponseOtpVerification)(nil), // 3: auth.ResponseOtpVerification
	(*SignUpRequest)(nil),           // 4: auth.SignUpRequest
	(*SignUpResponse)(nil),          // 5: auth.SignUpResponse
	(*RequestForgotPass)(nil),       // 6: auth.RequestForgotPass
	(*ResponseForgotPass)(nil),      // 7: auth.ResponseForgotPass
	(*RequestResetPass)(nil),        // 8: auth.RequestResetPass
	(*ResponseResetPass)(nil),       // 9: auth.ResponseResetPass
}
var file_pkg_infrastructure_pb_auth_server_proto_depIdxs = []int32{
	4, // 0: auth.AuthService.UserSignUp:input_type -> auth.SignUpRequest
	2, // 1: auth.AuthService.UserOTPVerication:input_type -> auth.RequestOtpVefification
	0, // 2: auth.AuthService.UserLogin:input_type -> auth.RequestUserLogin
	6, // 3: auth.AuthService.ForgotPasswordRequest:input_type -> auth.RequestForgotPass
	8, // 4: auth.AuthService.ResetPassword:input_type -> auth.RequestResetPass
	5, // 5: auth.AuthService.UserSignUp:output_type -> auth.SignUpResponse
	3, // 6: auth.AuthService.UserOTPVerication:output_type -> auth.ResponseOtpVerification
	1, // 7: auth.AuthService.UserLogin:output_type -> auth.ResponseUserLogin
	7, // 8: auth.AuthService.ForgotPasswordRequest:output_type -> auth.ResponseForgotPass
	9, // 9: auth.AuthService.ResetPassword:output_type -> auth.ResponseResetPass
	5, // [5:10] is the sub-list for method output_type
	0, // [0:5] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_pkg_infrastructure_pb_auth_server_proto_init() }
func file_pkg_infrastructure_pb_auth_server_proto_init() {
	if File_pkg_infrastructure_pb_auth_server_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_infrastructure_pb_auth_server_proto_rawDesc), len(file_pkg_infrastructure_pb_auth_server_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_infrastructure_pb_auth_server_proto_goTypes,
		DependencyIndexes: file_pkg_infrastructure_pb_auth_server_proto_depIdxs,
		MessageInfos:      file_pkg_infrastructure_pb_auth_server_proto_msgTypes,
	}.Build()
	File_pkg_infrastructure_pb_auth_server_proto = out.File
	file_pkg_infrastructure_pb_auth_server_proto_goTypes = nil
	file_pkg_infrastructure_pb_auth_server_proto_depIdxs = nil
}
